#!/bin/bash

local slot="-2"
local cp=""
local main_class=""
local xflag=""

case $0 in
    "dumpxsb${slot}")
        main_class="org.apache.xmlbeans.impl.tool.XsbDumper"
        ;;
    "inst2xsd${slot}")
        main_class="org.apache.xmlbeans.impl.inst2xsd.Inst2Xsd"
        ;;
    "scomp${slot}")
        main_class="org.apache.xmlbeans.impl.tool.SchemaCompiler"
        ;;
    "scopy${slot}")
        main_class="org.apache.xmlbeans.impl.tool.SchemaCopy"
        ;;
    "sdownload${slot}")
        main_class="org.apache.xmlbeans.impl.tool.SchemaResourceManager"
        ;;
    "sfactor${slot}")
        main_class="org.apache.xmlbeans.impl.tool.FactorImports"
        ;;
    "svalidate${slot}")
        main_class="org.apache.xmlbeans.impl.tool.StreamInstanceValidator"
        ;;
    "validate${slot}")
        main_class="org.apache.xmlbeans.impl.tool.InstanceValidator"
        ;;
    "xpretty${slot}")
        main_class="org.apache.xmlbeans.impl.tool.PrettyPrinter"
        ;;
    "xsd2inst${slot}")
        main_class="org.apache.xmlbeans.impl.xsd2inst.SchemaInstanceGenerator"
        ;;
    "xsdtree${slot}")
        main_class="org.apache.xmlbeans.impl.tool.TypeHierachyPrinter"
        xflags="-Xmx256m"
        ;;
    "xstc${slot}")
        main_class="org.apache.xmlbeans.impl.tool.XSTCTester"
        ;;
esac

cp=$(java-config -dp xml-xmlbeans${slot}):$(java-config -t)

exec $(java-config -J) ${xflags} -classpath ${cp} ${main_class} ${@}
