(require 'skewer-mode)
(require 'skewer-html)
(require 'skewer-css)
;(require 'skewer-setup)
;(skewer-setup)
(add-hook 'js2-mode-hook 'skewer-mode)
(add-hook 'css-mode-hook 'skewer-css-mode)
(add-hook 'html-mode-hook 'skewer-html-mode)
(add-hook 'web-mode-hook 'skewer-html-mode)
